
/*
* This source file was generated by the Gradle 'init' task
*/
package org.example.app
import org.apache.commons.text.WordUtils
import org.example.utilities.StringUtils
import com.moandjiezana.toml.Toml

// import com.
// import org.
fun main() {
    var someTomlStringText = """
        [server]
        ip = "127.0.0.1" # (required) the ip to bind to
        port = 8080 # (required) the port to bind to
        """

    var toml = Toml().read(someTomlStringText)

    var serverIp = toml.getString("server.ip")

    // Print the server ip in a formatted string
    println("Server IP: ${serverIp}")
}
